/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_achanzhang_free_ObjectJNI */

#ifndef _Included_com_achanzhang_free_ObjectJNI
#define _Included_com_achanzhang_free_ObjectJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_achanzhang_free_ObjectJNI
 * Method:    initInt2DArray
 * Signature: (I)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_com_achanzhang_free_ObjectJNI_initInt2DArray
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
