/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_achanzhang_free_IntArrayJNI */

#ifndef _Included_com_achanzhang_free_IntArrayJNI
#define _Included_com_achanzhang_free_IntArrayJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_achanzhang_free_IntArrayJNI
 * Method:    sumArray
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_achanzhang_free_IntArrayJNI_sumArray
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
